name: Python validator
on: [push, pull_request]
jobs:
  build:
    name: Validate Data
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout cbioportal repo'
        uses: actions/checkout@v2
        with:
          path: ./cbioportal
      - name: 'Checkout core module'
        uses: actions/checkout@v4
        with:
          path: ./cbioportal/core
          repository: cBioPortal/cbioportal-core
      - name: 'Validate tests'
        working-directory: ./cbioportal
        run: |
          docker run -v ${PWD}:/cbioportal python:3.6 /bin/sh -c '
            cd /cbioportal &&
            pip install -r requirements.txt &&
            export PYTHONPATH=/cbioportal/core/src/main/resources/scripts &&
            cd /cbioportal/core/src/test/scripts/ &&
            python unit_tests_validate_data.py &&
            python system_tests_validate_data.py &&
            python system_tests_validate_studies.py'